version: '3.8'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=damned123
      - POSTGRES_USER=damned
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 6543:5432
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./next.config.mjs

volumes:
  pgdata:
