version: '3.8'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
                - action: rebuild
                  path: ./package.json
                - action: rebuild
                  path: ./package-lock.json
                - action: rebuild
                  path: ./next.config.mjs
