version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hellodamned
    volumes:
      - pgData:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - '9000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db
      - nginx
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./next.config.mjs
volumes:
  pgData:
