name: Run Staging
on: [push]
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependies
        run: |
          echo "installing dependencies..."
          npm ci
      - name: Check prettier
        run: npx prettier . --check
      - name: Build and Push Docker image to GHCR
        uses: aleskxyz/build-push@v1
        with:
          image_name: ${{ github.event.repository.name }}
          registry_address: ghcr.io/${{ github.repository_owner }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ github.token }}
          platforms: linux/amd64, linux/arm64/v8
          context: .
